name: Node.js CI 

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x] 
        # what does the *.x stand for in these different node versions?
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # what does this do?
        
    - name: install project
      run: npm ci 
    
    - name: build a package
      run: npm run build --if-present
      
  test:
    runs-on: ubuntu-20.04
    
    steps:
    - name: run tests
      run: npm run test:unit
    
    
